--<ScriptOptions statementTerminator=";"/>


CREATE TABLE STUDENT_DETAIL (STUDENT_ID VARCHAR(6) NOT NULL,NAME VARCHAR(30),SUBJECT VARCHAR(30),SCORE INTEGER);
CREATE TABLE USER_DETAIL (USER_ID VARCHAR(6) NOT NULL,PASSWD VARCHAR(8)	);

